"""
Fixed PDF Report Generator
"""
from fpdf import FPDF
from datetime import datetime
import json

class DNAReportPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'DNA FORENSIC ANALYSIS REPORT', 0, 1, 'C')
        self.ln(5)
    
    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def generate_dna_report(data, output_path):
    """Generate a working PDF report"""
    try:
        pdf = DNAReportPDF()
        pdf.add_page()
        
        # Timestamp
        pdf.set_font('Arial', '', 10)
        pdf.cell(0, 8, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 0, 1, 'R')
        pdf.ln(5)
        
        # Sample Information
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, 'SAMPLE INFORMATION', 0, 1)
        pdf.set_font('Arial', '', 10)
        
        # Safe text extraction
        investigator = str(data.get('investigator_name', 'Unknown'))[:50]
        sample = str(data.get('sample_name', 'Sample'))[:50]
        prediction = str(data.get('prediction', 'N/A'))[:100]
        confidence = data.get('confidence', 0)
        
        pdf.cell(0, 6, f"Investigator: {investigator}", 0, 1)
        pdf.cell(0, 6, f"Sample Name: {sample}", 0, 1)
        pdf.cell(0, 6, f"Prediction: {prediction}", 0, 1)
        pdf.cell(0, 6, f"Confidence: {confidence*100:.2f}%", 0, 1)
        pdf.ln(5)
        
        # DNA Characteristics
        if 'dna_characteristics' in data and data['dna_characteristics']:
            pdf.set_font('Arial', 'B', 12)
            pdf.cell(0, 10, 'DNA CHARACTERISTICS', 0, 1)
            pdf.set_font('Arial', '', 10)
            
            dc = data['dna_characteristics']
            pdf.cell(0, 6, f"DNA Type: {dc.get('dna_type', 'N/A')}", 0, 1)
            pdf.cell(0, 6, f"Sequence Length: {dc.get('length', 0)} bp", 0, 1)
            pdf.cell(0, 6, f"GC Content: {dc.get('gc_content', 0)}%", 0, 1)
            pdf.cell(0, 6, f"Quality: {dc.get('quality', 'N/A')}", 0, 1)
            pdf.ln(5)
        
        # Blood Group
        if 'blood_group' in data and data['blood_group']:
            pdf.set_font('Arial', 'B', 12)
            pdf.cell(0, 10, 'BLOOD GROUP ANALYSIS', 0, 1)
            pdf.set_font('Arial', '', 10)
            
            bg = data['blood_group']
            pdf.cell(0, 6, f"Blood Group: {bg.get('blood_group', 'N/A')}", 0, 1)
            pdf.cell(0, 6, f"ABO Type: {bg.get('abo_type', 'N/A')}", 0, 1)
            pdf.cell(0, 6, f"Rh Factor: {bg.get('rh_factor', 'N/A')}", 0, 1)
            pdf.cell(0, 6, f"Detection Confidence: {bg.get('confidence', 0)*100:.1f}%", 0, 1)
            pdf.ln(5)
        
        # Confidence Assessment
        if 'confidence_assessment' in data:
            pdf.set_font('Arial', 'B', 12)
            pdf.cell(0, 10, 'ASSESSMENT', 0, 1)
            pdf.set_font('Arial', '', 10)
            
            ca = data['confidence_assessment']
            pdf.cell(0, 6, f"Status: {ca.get('status', 'N/A')}", 0, 1)
            pdf.multi_cell(0, 6, f"Recommendation: {ca.get('recommendation', 'N/A')[:200]}")
            pdf.ln(5)
        
        # Footer note
        pdf.ln(10)
        pdf.set_font('Arial', 'I', 8)
        pdf.multi_cell(0, 5, 'This report is generated by DNA Analysis System. Results should be verified by qualified professionals.')
        
        pdf.output(output_path)
        return output_path
        
    except Exception as e:
        print(f"PDF generation error: {e}")
        # Create a simple fallback PDF
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font('Arial', 'B', 16)
        pdf.cell(0, 10, 'DNA Analysis Report', 0, 1, 'C')
        pdf.set_font('Arial', '', 12)
        pdf.cell(0, 10, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 0, 1)
        pdf.cell(0, 10, f"Confidence: {data.get('confidence', 0)*100:.2f}%", 0, 1)
        pdf.output(output_path)
        return output_path
